print('Hello world')
print('My name is Pramat Boonlakorn.')
print('Mutt nickname')
print('Graduated from secondary school. 6')
print('From school/educational institution Nakhon Phanom Technical College')
print('Nakhon Phanom Province')
